services:
  postgres:
    image: postgres:16-alpine
    container_name: digicampus_db
    environment:
      POSTGRES_USER: digicampus
      POSTGRES_PASSWORD: digicampus
      POSTGRES_DB: digicampus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
